---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/forests":
    get:
      summary: Retrieves all forests
      tags:
      - Forests
      responses:
        '200':
          description: Forests found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    state:
                      type: string
                  required:
                  - id
                  - name
                  - state
            application/xml:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    state:
                      type: string
                  required:
                  - id
                  - name
                  - state
        '404':
          description: Forests not found
    post:
      summary: Create a forest
      tags:
      - Forests
      parameters: []
      responses:
        '201':
          description: Forests created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                state:
                  type: string
              required:
              - name
              - state
  "/forests/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Retrieve a forest
      tags:
      - Forests
      responses:
        '200':
          description: Forest Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  state:
                    type: string
                required:
                - id
                - name
                - state
        '404':
          description: Forest not Found
    put:
      summary: Updates a forest
      tags:
      - Forests
      parameters: []
      responses:
        '200':
          description: Forest updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                state:
                  type: string
              required:
              - name
              - state
    delete:
      summary: Deletes a forest
      tags:
      - Forests
      responses:
        '200':
          description: Forest deleted
        '404':
          description: Forest not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
